# Generated by Django 6.0.4 on 2026-05-05 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.FloatField(default=0.5)),
                ('total_submissions', models.IntegerField(default=0)),
                ('approved_submissions', models.IntegerField(default=0)),
                ('rejected_submissions', models.IntegerField(default=0)),
                ('duplicate_links_count', models.IntegerField(default=0)),
                ('suspicious_patterns_count', models.IntegerField(default=0)),
                ('fast_submissions_count', models.IntegerField(default=0)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('submission_frequency', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
