# Generated by Django 5.2.9 on 2026-05-02 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='review_notes',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requires_manual_review',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('share', 'Share'), ('post', 'Post')], default='share', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=5, help_text='Minutes to complete task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_slots',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together={('user', 'task')},
        ),
    ]
