# Generated by Django 6.0.4 on 2026-05-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_review_notes_tasksubmission_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='fraud_flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level1_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level1_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level2_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level2_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level3_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='level3_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('level1_pending', 'Level 1 Verification'), ('level2_pending', 'Level 2 Verification'), ('level3_pending', 'Level 3 Verification'), ('manual_review', 'Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
