# Generated by Django 5.2.9 on 2026-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_created_by_remove_task_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='group_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='group_visibility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
